<a href="https://colab.research.google.com/github/ameympatil/Pytorch/blob/main/Back_Propogation_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Back Propogation using PyTorch


In [8]:
import torch

In [9]:
x = torch.tensor(4.0,requires_grad=True)

In [10]:
x

tensor(4., requires_grad=True)

In [11]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [12]:
## Back Propogation 
## from y=x^2 to y=2*x

y.backward()

In [13]:
print(x.grad)

tensor(8.)


In [17]:
lst = [[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input = torch.tensor(lst,requires_grad=True)

In [18]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [19]:
## y = x^3 + x^2 ---->  y = 3x^2 + 2x
y = torch_input**3 + torch_input**2

In [20]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [22]:
z = y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [24]:
z.backward()

In [25]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])

In [27]:
3*1**2+2*1

5