<a href="https://colab.research.google.com/github/ameympatil/Pytorch/blob/main/PytorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import torch

In [35]:
# PyTorch version
torch.__version__

'1.13.1+cu116'

In [36]:
# Check GPU available
torch.cuda.is_available()

True

In [37]:
# Device ID
torch.cuda.current_device()

0

In [38]:
# GPU name
torch.cuda.get_device_name(0)

'Tesla T4'

In [39]:
# Memory allocated
torch.cuda.memory_allocated()

0

In [40]:
import numpy as np

In [41]:
lst = [3,4,5,6]
arr =np.array(lst)

In [42]:
arr

array([3, 4, 5, 6])

In [43]:
arr.dtype

dtype('int64')

In [44]:
# from numpy to tensors
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [45]:
tensors[:2]

tensor([3, 4])

In [46]:
tensors[3] = 100
arr

array([  3,   4,   5, 100])

In [47]:
# copy of array
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [48]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [49]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [50]:
# 2d array
a=torch.tensor(np.arange(0,15).reshape(5,3))
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [51]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

## Arithmetic Operation

In [57]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

print(a+b)

tensor([ 7.,  9., 11.])


In [58]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [59]:
c = torch.zeros(3)

In [60]:
torch.add(a,b).sum()

tensor(27.)

In [65]:
# Dot Product and Mul Operation
x = torch.tensor([3,4,5],dtype=torch.float)
y = torch.tensor([4,5,6],dtype=torch.float)

In [62]:
x.mul(y)

tensor([12., 20., 30.])

In [63]:
x.dot(y)

tensor(62.)

In [67]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [68]:
# Matrix multiplication
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [69]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [70]:
x@y

tensor([[55., 53.],
        [90., 92.]])